spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calculate_engine?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=True&characterEncoding=utf8
    #username: root
    #password: Wyh961130#
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080 # 设置端口号为8080
  servlet:
    context-path: /customCalculate # 设置应用的根目录为/customCalculate
